
spring:
  datasource:
    driver-class-name: ORG.postgresQL.cj.jdbc.Driver
    url: jdbc:postgresql://localhost}:5432/Schoolars
    username: postgres
    password: Main1!
  jpa:
    database:   POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true

server:
  port: 5432